### ISSUE TITLE
mozilla.org is blocked?

### ISSUE THREAD

**Issue by andrewiassur** [angela-d/autohosts#6]
i am unable to access mozilla.org with autohosts installed. i removed autohosts to confirm this issue. 
i grepped the /etc/hosts file 

cat /etc/hosts | grep mozilla.org
0.0.0.0 incoming.telemetry.mozilla.org
0.0.0.0 crash-stats.mozilla.org
0.0.0.0 experiments.mozilla.org
0.0.0.0 incoming.telemetry.mozilla.org
0.0.0.0 input.mozilla.org
0.0.0.0 self-repair.mozilla.org
0.0.0.0 tbpl.mozilla.org
0.0.0.0 telemetry.mozilla.org
0.0.0.0 reps.mozilla.org
0.0.0.0 intranet.mozilla.org
0.0.0.0 activations.mozilla.org
0.0.0.0 dnt.mozilla.org
0.0.0.0 www.mozilla.org.cdn.cloudflare.net
0.0.0.0 ftp.mozilla.org
0.0.0.0 mxr.mozilla.org
0.0.0.0 nightly.mozilla.org
0.0.0.0 pfs.mozilla.org
0.0.0.0 planet.mozilla.org
0.0.0.0 static-san.mozilla.org
0.0.0.0 videos.mozilla.org
0.0.0.0 mana.mozilla.org
0.0.0.0 symbols.mozilla.org
0.0.0.0 dxr.mozilla.org

why and how is mozilla.org blocked?
all of the output has subdomains of mozilla.org blocked but not mozilla.org blocked. how do i unblock this?

**Comment by angela-d** [comment]
Not able to reproduce on my machine, do you have anything in ~/autohosts/hosts_source?

Mine has:
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
https://raw.githubusercontent.com/angela-d/autohosts/master/firefox-includes

Please also post what version you're running - I think in earlier versions, the firefox-includes file was indeed blocking it.

**Comment by andrewiassur** [comment]
~/git-hub/autohosts$ ls
autohosts        firefox-includes  prior-v2-uninstall
autohosts-2.0.0  img               README.md
custom_filters   LICENSE           uninstall-authohosts

i'm assumeing version is 2.0.0 
doesnt look like there is a hosts_source

i updated it to the lastest version. that resolved my issue. i didnt realize there was different versions. 
thanks for your time.

**Comment by angela-d** [comment]
Awesome, glad it's fixed!

As there's bugfixes and improvements, new releases get pushed out.
